### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by reJELIN** [cbg-ethz/COMPASS#3]
Hi,

i'm very interested in your tools as i'm trying to develop a single-cell DNA pipeline analysis, i tried your tools on several samples but whenever i'm trying it always end with : 

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551613) > this->size() (which is 0)
Aborted (core dumped)
```

whether it have find no regions whose coverage in one node different from the root or identified candidates regions.

Am i doing something wrong ? Is there a reason. I'm working from data that have been sequence with tapestri pipeline but it have been sequence under hg19. From what i could read on your script it look like you're working with hg38 hg37.

**Comment by e-sollier** [comment]
Hi,

Thanks for your interest in COMPASS! 

COMPASS is agnostic to the reference genome used, so using hg19 should not cause any issue. 
Did you provide an output name with the` -o` command line argument ? I suspect that this might be what is causing your error, because this output name was required (even though I forgot to mention this in the readme). I have just pushed an update: now the output name is not required anymore, and the output will use the same basename as the input if no output name is provided.

Please let me know if using the latest COMPASS version or providing an output fixes your issue. If it does not, would you be able to share you processed data with me so that I can investigate the issue ?

**Comment by reJELIN** [comment]
Hi,

Thanks you for your answer, so i indeed use the -o argument command line, but i added a space that in between - and o that was the cause of this mistake.

but thanks to your answer i find it and correct it so thanks you !

**Comment by Zejian-Wang** [comment]
Hi @e-sollier ,

Hello!

I've encountered similar issues during my runs. Interestingly, the issue persists even when I omit the -o argument. Does this indicate a formatting problem with my copy-number input files? I've attempted to troubleshoot the input format but haven't identified any issues so far.

I attach my running file as below, please feel free to let me know if more information is needed! Thank you!

Best,

Zejian

```
`>COMPASS -i JoB185 --nchains 6 --chainlength 5000 --CNA 1 --sex male  

No output name was provided. COMPASS will use the same basename as the input for the output.
The following regions are excluded from the CNA inference because their coverage is too low: ATM,CDKN2A,CTNNB1,ELF3,ERBB2,ERCC2,FGFR3,KDM6A,RB1,RBM10,STAG2,TERT,TP53,
Starting 6 MCMC chains in parallel
Chain 0: Starting first phase (finding the best tree without CNA).
Chain 1: Starting first phase (finding the best tree without CNA).
Chain 2: Starting first phase (finding the best tree without CNA).
Chain 3: Starting first phase (finding the best tree without CNA).
Chain 5: Starting first phase (finding the best tree without CNA).
Chain 4: Starting first phase (finding the best tree without CNA).
Chain 1: After the first phase (inferring the best tree without CNAs), COMPASS identified the following candidate regions which might contain CNAs: KMT2D,KRAS,
Chain 1: Starting second phase (finding the best tree with CNA).
Chain 4: After the first phase (inferring the best tree without CNAs), COMPASS identified the following candidate regions which might contain CNAs: KMT2D,KRAS,
Chain 4: Starting second phase (finding the best tree with CNA).
Chain 2: After the first phase (inferring the best tree without CNAs), COMPASS identified the following candidate regions which might contain CNAs: KMT2D,KRAS,
Chain 2: Starting second phase (finding the best tree with CNA).
Chain 3: In the tree inferred without CNAs, there were no regions whose coverage in one node were different from the root, so COMPASS could not identify any CNAs.
Chain 5: After the first phase (inferring the best tree without CNAs), COMPASS identified the following candidate regions which might contain CNAs: KMT2D,KRAS,
Chain 5: Starting second phase (finding the best tree with CNA).
Chain 0: After the first phase (inferring the best tree without CNAs), COMPASS identified the following candidate regions which might contain CNAs: KMT2D,
Chain 0: Starting second phase (finding the best tree with CNA).
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)
Aborted (core dumped)`
```

This 'std::out_of_range' error also occurs when I set -o 

![image](https://github.com/cbg-ethz/COMPASS/assets/34888291/f76f4222-c728-4c79-9fe2-e7df5ac04cb8)

**Comment by e-sollier** [comment]
Hi @Zejian-Wang ,

would you be able to send me the full _variants.csv and _regions.csv files, so that I can figure out what went wrong ? Either as attachment here or by email to etienne "dot" sollier "at" dkfz "dot" de.
